//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetDataEntities : DbContext
    {
        public BudgetDataEntities()
            : base("name=BudgetDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ActualData> ActualDatas { get; set; }
        public virtual DbSet<ActualValue> ActualValues { get; set; }
        public virtual DbSet<Addition> Additions { get; set; }
        public virtual DbSet<Airfare> Airfares { get; set; }
        public virtual DbSet<Amortization> Amortizations { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AverageRate> AverageRates { get; set; }
        public virtual DbSet<BenefitData> BenefitDatas { get; set; }
        public virtual DbSet<BugReport> BugReports { get; set; }
        public virtual DbSet<Bursary> Bursaries { get; set; }
        public virtual DbSet<CapitalExpenditure> CapitalExpenditures { get; set; }
        public virtual DbSet<CapitalExpenditureComparison> CapitalExpenditureComparisons { get; set; }
        public virtual DbSet<CapitalExpenditureData> CapitalExpenditureDatas { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<CompanyGasMileage> CompanyGasMileages { get; set; }
        public virtual DbSet<CompanyGasMileageData> CompanyGasMileageDatas { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<ContractHour> ContractHours { get; set; }
        public virtual DbSet<CounsellingGroupType> CounsellingGroupTypes { get; set; }
        public virtual DbSet<CounsellingService> CounsellingServices { get; set; }
        public virtual DbSet<CounsellingServiceData> CounsellingServiceDatas { get; set; }
        public virtual DbSet<DeductionList> DeductionLists { get; set; }
        public virtual DbSet<DeductionType> DeductionTypes { get; set; }
        public virtual DbSet<DeferredAmortization> DeferredAmortizations { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Disposal> Disposals { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeBonu> EmployeeBonus { get; set; }
        public virtual DbSet<EmployeeDeduction> EmployeeDeductions { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual DbSet<EmployeeRaise> EmployeeRaises { get; set; }
        public virtual DbSet<EmployeeTarget> EmployeeTargets { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<ExistingHardware> ExistingHardwares { get; set; }
        public virtual DbSet<GAExpense> GAExpenses { get; set; }
        public virtual DbSet<GAExpenseComparison> GAExpenseComparisons { get; set; }
        public virtual DbSet<GAGroup> GAGroups { get; set; }
        public virtual DbSet<GasMileage> GasMileages { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupTherapyTarget> GroupTherapyTargets { get; set; }
        public virtual DbSet<GroupTherapyTarget1> GroupTherapyTargets1 { get; set; }
        public virtual DbSet<GSTRejection> GSTRejections { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HoursPerYear> HoursPerYears { get; set; }
        public virtual DbSet<InternTarget> InternTargets { get; set; }
        public virtual DbSet<LockedYear> LockedYears { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MealEntertainment> MealEntertainments { get; set; }
        public virtual DbSet<MiscTravel> MiscTravels { get; set; }
        public virtual DbSet<MonthlyGroup> MonthlyGroups { get; set; }
        public virtual DbSet<NonRevenueHour> NonRevenueHours { get; set; }
        public virtual DbSet<NonRevenueHourData> NonRevenueHourDatas { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramSection> ProgramSections { get; set; }
        public virtual DbSet<ProjectedFeePerHour> ProjectedFeePerHours { get; set; }
        public virtual DbSet<ResidentTarget> ResidentTargets { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenueComparison> RevenueComparisons { get; set; }
        public virtual DbSet<RevenueData> RevenueDatas { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SectionRevenueHour> SectionRevenueHours { get; set; }
        public virtual DbSet<ServiceExpense> ServiceExpenses { get; set; }
        public virtual DbSet<ServiceExpenseComparison> ServiceExpenseComparisons { get; set; }
        public virtual DbSet<ServiceExpenseData> ServiceExpenseDatas { get; set; }
        public virtual DbSet<TargetData> TargetDatas { get; set; }
        public virtual DbSet<UnchangingValue> UnchangingValues { get; set; }
        public virtual DbSet<UserBuiltSummary> UserBuiltSummaries { get; set; }
        public virtual DbSet<UserBuiltSummaryData> UserBuiltSummaryDatas { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorRecord> VendorRecords { get; set; }
        public virtual DbSet<WorkDay> WorkDays { get; set; }
    }
}
