//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalExpenditure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CapitalExpenditure()
        {
            this.CapitalExpenditure1 = new HashSet<CapitalExpenditure>();
            this.CapitalExpenditureComparisons = new HashSet<CapitalExpenditureComparison>();
            this.CapitalExpenditureDatas = new HashSet<CapitalExpenditureData>();
        }
    
        public int CapitalExpenditureID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> PoolID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapitalExpenditure> CapitalExpenditure1 { get; set; }
        public virtual CapitalExpenditure CapitalExpenditure2 { get; set; }
        public virtual Pool Pool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapitalExpenditureComparison> CapitalExpenditureComparisons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapitalExpenditureData> CapitalExpenditureDatas { get; set; }
    }
}
