//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public string Row { get; set; }
        public string Old { get; set; }
        public string New { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string User { get; set; }
        public string Name { get; set; }
    }
}
