//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonRevenueHourData
    {
        public int NonRevenueHourDataID { get; set; }
        public int TargetDataID { get; set; }
        public int NonRevenueHourID { get; set; }
        public int Value { get; set; }
    
        public virtual NonRevenueHour NonRevenueHour { get; set; }
        public virtual TargetData TargetData { get; set; }
    }
}
