//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pool()
        {
            this.Amortizations = new HashSet<Amortization>();
            this.CapitalExpenditures = new HashSet<CapitalExpenditure>();
            this.DeferredAmortizations = new HashSet<DeferredAmortization>();
        }
    
        public int PoolID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AccountNum { get; set; }
        public decimal DepreciationRate { get; set; }
        public Nullable<bool> StraightLine { get; set; }
        public bool C_isDeferred { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amortization> Amortizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapitalExpenditure> CapitalExpenditures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeferredAmortization> DeferredAmortizations { get; set; }
    }
}
