//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceExpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceExpense()
        {
            this.GSTRejections = new HashSet<GSTRejection>();
            this.ServiceExpense1 = new HashSet<ServiceExpense>();
            this.ServiceExpenseDatas = new HashSet<ServiceExpenseData>();
            this.ServiceExpenseComparisons = new HashSet<ServiceExpenseComparison>();
        }
    
        public int ServiceExpenseID { get; set; }
        public Nullable<int> AccountNum { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GSTRejection> GSTRejections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceExpense> ServiceExpense1 { get; set; }
        public virtual ServiceExpense ServiceExpense2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceExpenseData> ServiceExpenseDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceExpenseComparison> ServiceExpenseComparisons { get; set; }
    }
}
