//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBuiltSummaryData
    {
        public int Id { get; set; }
        public int SummaryID { get; set; }
        public string Name { get; set; }
        public string Table { get; set; }
        public int TableItemID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserBuiltSummary UserBuiltSummary { get; set; }
    }
}
