//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBuiltSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserBuiltSummary()
        {
            this.UserBuiltSummary1 = new HashSet<UserBuiltSummary>();
            this.UserBuiltSummaryDatas = new HashSet<UserBuiltSummaryData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBuiltSummary> UserBuiltSummary1 { get; set; }
        public virtual UserBuiltSummary UserBuiltSummary2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBuiltSummaryData> UserBuiltSummaryDatas { get; set; }
    }
}
