SET IDENTITY_INSERT [dbo].[Employee] ON
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (1, 1, NULL, NULL, N'Rochelle', N'Wagner', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (2, 1, NULL, NULL, N'Deborah', N'Kieran', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (3, 1, NULL, NULL, N'Rick', N'Westman', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (4, 1, NULL, NULL, N'Michelle', N'Keough', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (5, 1, NULL, NULL, N'Carla', N'Blaine', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (6, 1, NULL, NULL, N'Maureen', N'McWilliams', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (7, 1, NULL, NULL, N'Ashley', N'Bishop', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (8, 1, NULL, NULL, N'Chris', N'Berry', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (9, 1, NULL, NULL, N'Margaux', N'Gregson', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (10, 1, NULL, NULL, N'Tanya', N'Kang ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (11, 1, NULL, NULL, N'Vera', N'McCready ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (12, 1, NULL, NULL, N'Kim', N'Busch ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (13, 1, NULL, NULL, N'Cathy', N'Keough ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (14, 1, NULL, NULL, N'Alex', N'Cameron ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (15, 1, NULL, NULL, N'Sharla', N'Zamanowitz ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (16, 1, NULL, NULL, N'Thalia', N'Anderen ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (17, 1, NULL, NULL, N'Joanne', N'Ginter ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (18, 1, NULL, NULL, N'Lisa', N'Boag Guidi ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (19, 1, NULL, NULL, N'Jessica', N'Johnson ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (20, 1, NULL, NULL, N'Sebastian', N'Sewick ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (21, 1, NULL, NULL, N'Gail', N'Bailey ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (22, 1, NULL, NULL, N'Christine', N'Molohon ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (23, 1, NULL, NULL, N'Natalya', N'Austin ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (24, 1, NULL, NULL, N'Cristina', N'Kalas ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (25, 1, NULL, NULL, N'Marcus', N'Cheung ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (26, 1, NULL, NULL, N'Annemarie', N'Rued Fraser ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (27, 1, NULL, NULL, N'Harnoor', N'Parmar', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (28, 1, NULL, NULL, N'Aspen ', N'Gowers ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (29, 1, NULL, NULL, N'New counsellor ', N'may ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (30, 1, NULL, NULL, N'new counsellor ', N'july  ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (31, 1, NULL, NULL, N'New Counsellor ', N'6 ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (32, 1, NULL, NULL, N'New Counsellor ', N'7', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (34, 2, NULL, NULL, N'Bonnie ', N'Eckert ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (35, 2, NULL, NULL, N'Hengameh ', N'Zarafshan ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (36, 2, NULL, NULL, N'Kelsey ', N'Haworth ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (37, 2, NULL, NULL, N'Diana ', N'Chung ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (38, 2, NULL, NULL, N'Jen ', N'Gray ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (39, 2, NULL, NULL, N'Rachael ', N'Benton ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (40, 2, NULL, NULL, N'Lauren ', N'Tokarek ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (41, 2, NULL, NULL, N'Ruth ', N'Nielsen ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (42, 2, NULL, NULL, N'Cynthia ', N'Runke ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (43, 2, NULL, NULL, N'New ', N'Admin ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (44, 2, NULL, NULL, N'Monica ', N'Cornejo ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (45, 2, NULL, NULL, N'Jillian ', N'Tabbert ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (47, 3, NULL, NULL, N'Sandy ', N'Berzins ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (48, 3, NULL, NULL, N'Tran ', N'Pham ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (49, 3, NULL, NULL, N'Emma ', N'Truscott ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (50, 3, NULL, NULL, N'Karissa ', N'Nyman ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (52, 4, NULL, NULL, N'Leighton ', N'Klassen ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (53, 4, NULL, NULL, N'Tara ', N'Linsley ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (54, 4, NULL, NULL, N'Tyler ', N'Skrabek ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (55, 4, NULL, NULL, N'Joanna ', N'Byers ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (56, 4, NULL, NULL, N'New Communications ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (58, 5, NULL, NULL, N'Katrina ', N'Bradley', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (59, 5, NULL, NULL, N'Caitlin ', N'Simpson', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (60, 5, NULL, NULL, N'Fund Development ', N'Officer', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (61, 5, NULL, NULL, N'Kim ', N'McAdam', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (63, 6, NULL, NULL, N'Deanna ', N'Holt ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (64, 6, NULL, NULL, N'Jessica ', N'Morozoff ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (65, 6, NULL, NULL, N'Margaux ', N'Gregson ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (66, 6, NULL, NULL, N'Allie ', N'Caputo ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (67, 6, NULL, NULL, N'New Intake', N' 2 ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (69, 7, NULL, NULL, N'John ', N'Ang ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (70, 7, NULL, NULL, N'New ', N'IT ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (71, 7, NULL, NULL, N'New ', N'IT 2 ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (73, 8, NULL, NULL, N'Counsellor ', N'1 ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (74, 8, NULL, NULL, N'Counsellor', N'2 ', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (75, 8, NULL, NULL, N'Communications ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (76, 8, NULL, NULL, N'Desktop ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (77, 8, NULL, NULL, N'Reserach ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (78, 8, NULL, NULL, N'IT ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (79, 8, NULL, NULL, N'manuals ', N'1', NULL, NULL)
INSERT INTO [dbo].[Employee] ([EmployeeID], [DepartmentID], [TypeID], [BenefitPlanID], [FirstName], [LastName], [StartDate], [EndDate]) VALUES (80, 8, NULL, NULL, N'summer', N'extra 2', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Employee] OFF
