CREATE TABLE [dbo].[ChangeLog]
(
	[Id] INT NOT NULL IDENTITY(1, 1), 
	[URL] NVARCHAR(100) NOT NULL, 
	[Row] NVARCHAR(50) NOT NULL, 
	[Old] NVARChar(50) NOT NULL, 
	[New] NVARCHAR(50) NOT NULL,
	[TimeStamp] DATETIME NOT NULL, 
	[User] NVARCHAR(50) NOT NULL, 
	[Name] NVARCHAR(50) NULL, 
	PRIMARY KEY CLUSTERED([Id] ASC) 
)
